export const FETCH_ARTISTS_INIT = 'FETCH_ARTISTS_INIT'
export const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTISTS_SUCCESS'
export const FETCH_ARTISTS_FAIL = 'FETCH_ARTISTS_FAIL'

export const FETCH_ALBUMS_INIT = 'FETCH_ALBUMS_INIT'
export const FETCH_ALBUMS_SUCCESS = 'FETCH_ALBUMS_SUCCESS'
export const FETCH_ALBUMS_FAIL = 'FETCH_ALBUMS_FAIL'
export const FETCH_ARTIST_SUCCESS = 'FETCH_ARTIST_SUCCESS'
export const FETCH_ARTIST_FAIL = 'FETCH_ARTIST_FAIL'

export const FETCH_TRACKS_INIT = 'FETCH_TRACKS_INIT'
export const FETCH_TRACKS_SUCCESS = 'FETCH_TRACKS_SUCCESS'
export const FETCH_TRACKS_FAIL = 'FETCH_TRACKS_FAIL'
export const FETCH_ALBUM_SUCCESS = 'FETCH_ALBUM_SUCCESS'
export const FETCH_ALBUM_FAIL = 'FETCH_ALBUM_FAIL'

export const CHANGE_ARTIST_PAGE = 'CHANGE_ARTIST_PAGE'
export const CHANGE_ALBUM_PAGE = 'CHANGE_ALBUM_PAGE'
export const FIRST_PAGE = 'FIRST_PAGE'